version: '3'

services:

  api:
      container_name: 'backend-api'
      build: .
      ports:
        - ${API_PORT}:${API_PORT}
      volumes:
        - .:/home/api
      environment:
          - DATABASE_URL=${DATABASE_URL_API}

  database:
    container_name: 'backend-database'
    image: 'postgres:13-alpine'
    environment:
      - POSTGRES_USER=${PRISMA_USERNAME}
      - POSTGRES_PASSWORD=${PRISMA_PASSWORD}
      - POSTGRES_DB=${PRISMA_DATABASE}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - ${PRISMA_PORT}:5432
    restart: unless-stopped
